# Generated by Django 5.1.2 on 2024-10-31 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id_solution', models.AutoField(primary_key=True, serialize=False)),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.answer')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.question')),
            ],
        ),
    ]
